// src/lib/data.ts -- REFINED WITH CASE STUDY FORMAT

export const projectsData = [
  {
    id: 1,
    title: "Moleskine",
    tagline: "High-Performance E-commerce Platform",
    description: "Moleskine is a global stationery brand that sells premium notebooks, planners, writing tools, bags, and related accessories through its official e-commerce site and retail network.",
    features: [
      "Robust Google OAuth Authentication",
      "Instant Live Search (<300ms)",
      "Smart notebooks and digital-planner products",
      "Shipping, returns, and customer support",
      "Journals, planners, and limited-edition designs",
      "Personalized notebooks and gift options",
    ],
    stack: [
      "CMS",
      "Payment gateways",
      "JavaScript",
      "HTML5",
      "CDN",
      "SSL",
    ],
    image: "/projects/soft-sale.png",
    liveSiteUrl: "https://www.moleskine.com/en-us/",
  },
  {
    id: 2,
    title: "Steam Store",
    tagline: "Large-scale entertainment site1",
    description: "Steam is a digital distribution platform and storefront for video games and related digital content, operated by Valve Corporation. Through its online store, it offers a massive catalog of games, downloadable content (DLC), and software to users worldwide.",
    features: [
      "Browse and discover games",
      "Steam Store features",
      "User accounts & social tools",
      "Wishlist, cart, and payments",
      "Wide game support",
    ],
    stack: [
      "C++ Backend",
      "Python",
      "JavaScript + HTML/CSS Frontend",
      "Steamworks Web API",
      "Content Delivery Network (CDN)",
      "SQL + Distributed Databases",
    ],
    image: "/projects/soft-game1.png",
    liveSiteUrl: "https://store.steampowered.com/",
  },
  {
    id: 3,
    title: "itch.io",
    tagline: "Large-scale entertainment site2",
    description: "Itch.io is a digital distribution marketplace and platform focused on indie video games — but also hosting game assets, music, comics, zines, and other digital creative content. It was founded in 2013 by Leaf Corcoran.",
    features: [
      "Open to all creators to sell or share content at any price.",
      "Lets creators publish bundles and web-playable versions.",
      "Friendly for indie developers and unique, niche content.",
      "Creators of any size can upload and price their work freely.",
      "Popular among small teams and hobby creators.",
      "Supports multi-item bundles and web-based games.",
    ],
    stack: [
      "Lua / MoonScript Backend",
      "OpenResty (Nginx + Lua)",
      "Asynchronous I/O + Coroutines",
      "Cloud Storage + CDN",
      "Frontend Web Stack (HTML / CSS / JavaScript)",
      "Frontend Web Stack (HTML / CSS / JavaScript)",
    ],
    image: "/projects/soft-game2.png",
    liveSiteUrl: "https://itch.io/",
  },
];